### ISSUE TITLE
Todos los usuarios pueden eliminar, modificar cualquier mensaje.

### ISSUE THREAD

**Issue by segura2010** [Push-EDX/flarum-ext-restricted-reply#1]
https://github.com/Push-EDX/flarum-ext-restricted-reply/blob/master/src/Access/RestrictedReplyPolicy.php#L60

Debe comprobarse que el usuario realmente tiene permiso para llevar a cabo la acción concreta. Si siempre se devuelve 'true', se esta permitiendo que el usuario tenga permisos para cualquier opción (editar, eliminar, etc)

**Comment by gpascualg** [comment]
Había asumido que las demás pólizas seguirían ejecutándose y que debían cumplirse todas, pero veo
https://github.com/flarum/core/blob/master/src/Core/Access/Gate.php#L214

Que en cuanto se cumple una las demás ya no ejecutan... No me acaba de convencer este sistema, ahora tendré que duplicar código para que esto funcione...

Gracias!

EDIT: Mentida, bastará con no  devolver nada en los otros casos, y así sí correrán las otras pólizas!

Algo así debería ser suficiente a08d17cf6e2dfa55fb95c11258106c9bf623f1a6
De nuevo gracias ;)

**Comment by gpascualg** [comment]
Arreglado y comprobado, cierro!

**Comment by segura2010** [comment]
De nada! He entrado al foro y lo he visto, así que he venido a ver que pasaba :) Si tuviese algo de tiempo lo hubiese intentado arreglar.

Gracias por crear el foro!
